import { useEffect, useState } from "react";
import { BookOpen, LoaderCircle } from "lucide-react";
import api from "../../api";
import { buttonClass, inputClass } from "../../constants/ui";
import { errorMessage } from "../../utils/formatters";
import Field from "../../components/ui/Field";
export default function AccessPage({onReady}) {
  const [setup,setSetup]=useState(null),[form,setForm]=useState({name:"",email:"",password:"",department:""}),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{void api.get("/setup/status").then(r=>setSetup(r.data.required)).catch(e=>setError(errorMessage(e)));},[]);
  const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{if(setup){await api.post("/setup",form);setSetup(false);setForm({...form,name:"",password:""});}else{const {data}=await api.post("/auth/login",form);localStorage.setItem("token",data.token);localStorage.setItem("user",JSON.stringify(data.user));onReady(data.user);}}catch(err){setError(errorMessage(err));}finally{setBusy(false);}};
  if(setup===null&&!error)return <div className="grid min-h-screen place-items-center"><LoaderCircle className="animate-spin text-teal-700"/></div>;
  return <div className="grid min-h-screen bg-slate-100 lg:grid-cols-2"><div className="hidden bg-gradient-to-br from-teal-900 to-slate-900 p-14 text-white lg:flex lg:flex-col lg:justify-between"><BookOpen size={42}/><div><p className="text-sm font-bold uppercase tracking-[.25em] text-teal-300">Haridwar University</p><h1 className="mt-4 font-display text-5xl font-extrabold">Student progression, completely connected.</h1></div><p className="text-xs text-teal-200">MentorConnect · University progression portal</p></div><div className="grid place-items-center p-5"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white p-8 shadow-soft"><h2 className="font-display text-3xl font-extrabold">{setup?"Create administrator":"Welcome back"}</h2>{error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-6 space-y-4">{setup&&<Field label="Full name"><input className={inputClass} required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field>}<Field label="Email"><input className={inputClass} type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Password"><input className={inputClass} type="password" minLength="8" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field>{setup&&<Field label="Department"><input className={inputClass} value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></Field>}</div><button disabled={busy} className={`${buttonClass} mt-6 w-full bg-teal-700 text-white`}>{busy&&<LoaderCircle size={17} className="animate-spin"/>}{setup?"Create and continue":"Sign in"}</button></form></div></div>;
}
