import { Router } from "express";
import { setupStatus, setup, login, me, updateMe } from "../controllers/authController.js";
import { authenticate } from "../middleware/auth.js";
import { asyncHandler } from "../utils/asyncHandler.js";
const router = Router();
router.get("/setup/status", asyncHandler(setupStatus));
router.post("/setup", asyncHandler(setup));
router.post("/auth/login", asyncHandler(login));
router.get("/auth/me", authenticate, me);
router.patch("/auth/me", authenticate, asyncHandler(updateMe));
export default router;
