import { Router } from "express";
import mongoose from "mongoose";
import authRoutes from "./authRoutes.js";
import userRoutes from "./userRoutes.js";
import studentRoutes from "./studentRoutes.js";
import sessionRoutes from "./sessionRoutes.js";
import { resourceRouter } from "./resourceRoutes.js";
import { Academic, Record, Assessment } from "../models/index.js";
import { authenticate } from "../middleware/auth.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { dashboard } from "../controllers/dashboardController.js";
import { studentReport } from "../controllers/reportController.js";

const router = Router();
router.get("/health", (_req, res) => res.json({ status: mongoose.connection.readyState === 1 ? "ok" : "unavailable", database: mongoose.connection.readyState === 1 ? "connected" : "disconnected" }));
router.use(authRoutes);
router.use("/users", userRoutes);
router.use("/students", studentRoutes);
router.use("/sessions", sessionRoutes);
router.use("/academics", resourceRouter(Academic, ["admin", "hod", "mentor"]));
router.use("/records", resourceRouter(Record, ["admin", "hod", "mentor", "student"]));
router.use("/assessments", resourceRouter(Assessment, ["admin", "hod", "mentor", "student"], true));
router.get("/dashboard", authenticate, asyncHandler(dashboard));
router.get("/reports/student/:id", authenticate, asyncHandler(studentReport));
export default router;
