import { useCallback, useState } from "react";
import { LayoutDashboard, Users, CalendarDays, GraduationCap, Trophy, MessageSquareText, BarChart3, Settings, UserCog, BookOpen, LogOut, Menu, Bell } from "lucide-react";
import Toast from "../components/ui/Toast";
import { initials } from "../utils/formatters";
import { DashboardPage, StudentsPage, SessionsPage, AcademicsPage, RecordsPage, AssessmentsPage, ReportsPage, UsersPage, SettingsPage } from "../pages";
const navigation=[["Dashboard",LayoutDashboard],["Students",Users],["Sessions",CalendarDays],["Academics",GraduationCap],["Records",Trophy],["Assessments",MessageSquareText],["Reports",BarChart3],["Users",UserCog],["Settings",Settings]];
const pages={Dashboard:DashboardPage,Students:StudentsPage,Sessions:SessionsPage,Academics:AcademicsPage,Records:RecordsPage,Assessments:AssessmentsPage,Reports:ReportsPage,Users:UsersPage,Settings:SettingsPage};
export default function AppShell({user,setUser}) {
  const [active,setActive]=useState("Dashboard"),[mobile,setMobile]=useState(false),[toast,setToast]=useState(null);
  const notify=useCallback((text,type="success")=>setToast({text,type}),[]);
  const clearToast=useCallback(()=>setToast(null),[]);
  const allowed=navigation.filter(([name])=>name!=="Users"||["admin","hod"].includes(user.role));
  const CurrentPage=pages[active];
  const logout=()=>{localStorage.clear();setUser(null);};
  return <div className="min-h-screen bg-[#f4f7f6]"><Toast toast={toast} clear={clearToast}/>{mobile&&<button className="fixed inset-0 z-30 bg-black/40 lg:hidden" onClick={()=>setMobile(false)}/>}<aside className={`fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r bg-white p-4 transition-transform lg:translate-x-0 ${mobile?"translate-x-0":"-translate-x-full"}`}><div className="flex items-center gap-3 px-2 py-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-teal-700 text-white"><BookOpen size={20}/></div><div><b>MentorConnect</b><p className="text-[9px] font-bold uppercase text-teal-700">Haridwar University</p></div></div><nav className="mt-6 space-y-1">{allowed.map(([name,Icon])=><button key={name} onClick={()=>{setActive(name);setMobile(false);}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold ${active===name?"bg-teal-50 text-teal-800":"text-slate-500"}`}><Icon size={18}/>{name}</button>)}</nav><div className="mt-auto rounded-2xl bg-slate-900 p-4 text-white"><div className="flex gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-teal-700 text-xs font-bold">{initials(user.name)}</div><div><p className="text-sm font-bold">{user.name}</p><p className="text-[10px] uppercase text-slate-400">{user.role}</p></div></div><button onClick={logout} className="mt-4 flex items-center gap-2 text-xs"><LogOut size={14}/>Sign out</button></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-[70px] items-center border-b bg-white/90 px-4 md:px-8"><button className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></button><div className="ml-auto flex items-center gap-3"><Bell size={18}/><div className="text-right"><p className="text-sm font-bold">{user.name}</p><p className="text-[10px] uppercase text-slate-400">{user.department||user.role}</p></div></div></header><main className="mx-auto max-w-[1500px] p-4 md:p-8"><CurrentPage user={user} notify={notify}/></main></div></div>;
}
